# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EmployeeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmployeeApp
  pod 'Alamofire', '~> 5.9.1'
  pod 'R.swift', '~> 7.3.2'
  pod 'IQKeyboardManagerSwift', '~> 7.0.3'
  pod 'SVProgressHUD', '~> 2.3.1'
  pod 'SDWebImage', '~> 5.0'
  pod 'lottie-ios', '~> 4.4.3'
  pod 'RealmSwift', '~> 10.52.0'
  pod 'PureLayout', '~> 3.1.9'
  pod 'TagListView', '~> 1.4.1'
  pod 'StorageManager', '~> 0.1.7'
  
  # Firebase
  pod 'FirebaseAuth', '~> 10.29.0'
  pod 'FirebaseFirestore', '~> 10.29.0'
  pod 'FirebaseAnalytics', '~> 10.28.0'
  pod 'FirebaseStorage', '~> 10.29.0'
  
  # Combine
  pod 'CombineCocoa', '~> 0.4.1'
  pod 'NSObject+Combine', '~> 1.0.1'
  
  # Check for JailBroken Devices
  pod 'IOSSecuritySuite', '1.9.11'
  
  # Material Design Components
  pod 'MaterialComponents/Buttons', '~> 124.2.0'
  pod 'MaterialComponents/Buttons+Theming', '~> 124.2.0'
  pod 'MaterialComponents/TextFields', '~> 124.2.0'
  pod 'MaterialComponents/TextFields+Theming', '~> 124.2.0'
  pod 'MaterialComponents/Snackbar', '~> 124.2.0'

  target 'EmployeeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EmployeeAppUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
