# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EmployeeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmployeeApp
  pod 'Alamofire', '~> 5.9.1'
  pod 'R.swift', '~> 7.3.2'
  pod 'IQKeyboardManagerSwift', '~> 7.0.3'
  pod 'SVProgressHUD', '~> 2.3.1'
  pod 'SDWebImage', '~> 5.0'
  pod 'FirebaseAuth', '~> 10.29.0'
  pod 'FirebaseFirestore', '~> 10.29.0'
  pod 'FirebaseAnalytics', '~> 10.28.0'

  target 'EmployeeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EmployeeAppUITests' do
    # Pods for testing
  end

end
